<?php
error_reporting(0);
ini_set('display_errors', 0);

require_once '../includes/config.php';

$document_id = isset($_GET['document_id']) ? intval($_GET['document_id']) : 0;

if (!$document_id) {
    die('Document ID is required');
}

try {
    $db = getDB();
    
    // Get document info
    $stmt = $db->prepare("SELECT * FROM documents WHERE id = ?");
    $stmt->execute([$document_id]);
    $document = $stmt->fetch();
    
    if (!$document) {
        die('Document not found');
    }
    
    // Get signature
    $stmt = $db->prepare("SELECT signature_image_path, signer_name, signed_at FROM signature_audit WHERE document_id = ? ORDER BY signed_at DESC LIMIT 1");
    $stmt->execute([$document_id]);
    $signature = $stmt->fetch();
    
    // Get filled content
    $displayContent = '';
    
    if ($document['filled_path'] && file_exists($document['filled_path'])) {
        $ext = strtolower(pathinfo($document['filled_path'], PATHINFO_EXTENSION));
        if ($ext == 'docx') {
            $zip = new ZipArchive();
            if ($zip->open($document['filled_path']) === true) {
                $xml = $zip->getFromName('word/document.xml');
                $zip->close();
                $displayContent = strip_tags($xml);
                $displayContent = html_entity_decode($displayContent, ENT_QUOTES, 'UTF-8');
            }
        } elseif ($ext == 'txt') {
            $displayContent = file_get_contents($document['filled_path']);
        }
    } elseif ($document['original_path'] && file_exists($document['original_path'])) {
        $ext = strtolower(pathinfo($document['original_path'], PATHINFO_EXTENSION));
        if ($ext == 'docx') {
            $zip = new ZipArchive();
            if ($zip->open($document['original_path']) === true) {
                $xml = $zip->getFromName('word/document.xml');
                $zip->close();
                $displayContent = strip_tags($xml);
                $displayContent = html_entity_decode($displayContent, ENT_QUOTES, 'UTF-8');
            }
        } elseif ($ext == 'txt') {
            $displayContent = file_get_contents($document['original_path']);
        }
    }
    
    // Generate HTML for download
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>' . htmlspecialchars($document['original_filename']) . '</title>
        <style>
            body {
                font-family: "Times New Roman", Times, serif;
                font-size: 12pt;
                line-height: 1.5;
                margin: 40px;
            }
            .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid #1A2A4A;
                padding-bottom: 10px;
            }
            .content {
                margin-bottom: 30px;
                white-space: pre-wrap;
            }
            .signature-section {
                margin-top: 50px;
                border-top: 1px solid #ccc;
                padding-top: 20px;
            }
            .signature-image {
                max-width: 200px;
                max-height: 80px;
                margin-top: 10px;
            }
            .footer {
                margin-top: 50px;
                text-align: center;
                font-size: 9pt;
                color: #999;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>' . htmlspecialchars($document['original_filename']) . '</h1>
            <p>Finalized: ' . date('Y-m-d H:i:s') . '</p>
        </div>
        
        <div class="content">
            <pre style="white-space:pre-wrap;">' . htmlspecialchars($displayContent) . '</pre>
        </div>
        
        <div class="signature-section">
            <h3>Digital Signature</h3>
            <p><strong>Signed by:</strong> ' . htmlspecialchars($signature['signer_name'] ?? 'Unknown') . '</p>
            <p><strong>Date Signed:</strong> ' . date('F j, Y g:i A', strtotime($signature['signed_at'] ?? 'now')) . '</p>';
    
    if ($signature && $signature['signature_image_path'] && file_exists($signature['signature_image_path'])) {
        $imageData = base64_encode(file_get_contents($signature['signature_image_path']));
        $html .= '<p><strong>Signature:</strong></p>
                  <img src="data:image/png;base64,' . $imageData . '" class="signature-image" alt="Signature">';
    }
    
    $html .= '
        </div>
        
        <div class="footer">
            This document was digitally signed and verified. Generated by DocSign System.
        </div>
    </body>
    </html>';
    
    // Save and download
    $downloadPath = TEMP_DIR . 'signed_document_' . $document_id . '.html';
    file_put_contents($downloadPath, $html);
    
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="signed_document_' . $document_id . '.html"');
    header('Content-Length: ' . filesize($downloadPath));
    readfile($downloadPath);
    unlink($downloadPath);
    exit;
    
} catch(Exception $e) {
    die('Error: ' . $e->getMessage());
}
?>